name: 'create-tag'

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: |
          npm install

      - run: |
          npm run all
        env:
          NODE_ENV: 'production'
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OWNER: ${{ secrets.TEST_OWNER }}
          REPO: ${{ secrets.TEST_REPO }}

      - name: Logging github.ref
        run: |
          echo "github.ref=${{ github.ref }}"

      - name: Get next version
        uses: ./
        id: next_version_proposal
        with:
          github_token: ${{ github.token }}
          major_labels: 'major, next'
          minor_labels: 'feature, enhancement'
          patch_labels: 'bug, dependencies, chore, documentation'
          next_version_prefix: 'v'

      - name: Create or update tag major
        uses: rickstaa/action-create-tag@v1
        if: ${{ (steps.next_version_proposal.outputs.next_version != '') && (steps.next_version_proposal.outputs.next_version_major != '') }}
        with:
          tag: 'v${{ steps.next_version_proposal.outputs.next_version_major }}'
          message: 'Overwrite v${{ steps.next_version_proposal.outputs.next_version_major }}'
          commit_sha: ${{ github.sha }}
          force_push_tag: true

      - name: Create or update tag major.minor
        uses: rickstaa/action-create-tag@v1
        if: ${{ (steps.next_version_proposal.outputs.next_version != '') && (steps.next_version_proposal.outputs.next_version_major != '') && (steps.next_version_proposal.outputs.next_version_minor != '') }}
        with:
          tag: 'v${{ steps.next_version_proposal.outputs.next_version_major }}.${{ steps.next_version_proposal.outputs.next_version_minor }}'
          message: 'Overwrite v${{ steps.next_version_proposal.outputs.next_version_major }}.${{ steps.next_version_proposal.outputs.next_version_minor }}'
          commit_sha: ${{ github.sha }}
          force_push_tag: true

      - name: Create tag current
        uses: rickstaa/action-create-tag@v1
        if: ${{ steps.next_version_proposal.outputs.next_version != '' }}
        with:
          tag: '${{ steps.next_version_proposal.outputs.next_version }}'
          message: 'New release ${{ steps.next_version_proposal.outputs.next_version }}'
          commit_sha: ${{ github.sha }}

      - name: create GitHub Release
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        if: ${{ steps.next_version_proposal.outputs.next_version != '' }}
        with:
          config-name: release-drafter.yml
          version: ${{ steps.next_version_proposal.outputs.next_version }}
          publish: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: git tag skipped
        if: ${{ steps.next_version_proposal.outputs.next_version == '' }}
        run: |
          echo "Next version tag is empty."
